// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddFileMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum AddFileRsp_ResultCode

typedef GPB_ENUM(AddFileRsp_ResultCode) {
  AddFileRsp_ResultCode_Success = 0,
  AddFileRsp_ResultCode_Fail = 1,
};

GPBEnumDescriptor *AddFileRsp_ResultCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL AddFileRsp_ResultCode_IsValidValue(int32_t value);

#pragma mark - AddFileMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AddFileMsgRoot : GPBRootObject
@end

#pragma mark - AddFileReq

typedef GPB_ENUM(AddFileReq_FieldNumber) {
  AddFileReq_FieldNumber_FileId = 1,
  AddFileReq_FieldNumber_FileName = 2,
  AddFileReq_FieldNumber_FileInfo = 3,
  AddFileReq_FieldNumber_FileSize = 4,
  AddFileReq_FieldNumber_FileDate = 5,
  AddFileReq_FieldNumber_UserId = 6,
  AddFileReq_FieldNumber_FileURL = 7,
  AddFileReq_FieldNumber_FilePwd = 8,
};

@interface AddFileReq : GPBMessage

@property(nonatomic, readwrite) int32_t fileId;

@property(nonatomic, readwrite) BOOL hasFileId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileName;
/** Test to see if @c fileName has been set. */
@property(nonatomic, readwrite) BOOL hasFileName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileInfo;
/** Test to see if @c fileInfo has been set. */
@property(nonatomic, readwrite) BOOL hasFileInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileSize;
/** Test to see if @c fileSize has been set. */
@property(nonatomic, readwrite) BOOL hasFileSize;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileDate;
/** Test to see if @c fileDate has been set. */
@property(nonatomic, readwrite) BOOL hasFileDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;
/** Test to see if @c userId has been set. */
@property(nonatomic, readwrite) BOOL hasUserId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileURL;
/** Test to see if @c fileURL has been set. */
@property(nonatomic, readwrite) BOOL hasFileURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *filePwd;
/** Test to see if @c filePwd has been set. */
@property(nonatomic, readwrite) BOOL hasFilePwd;

@end

#pragma mark - AddFileRsp

typedef GPB_ENUM(AddFileRsp_FieldNumber) {
  AddFileRsp_FieldNumber_ResultCode = 1,
  AddFileRsp_FieldNumber_FileName = 2,
  AddFileRsp_FieldNumber_FileInfo = 3,
  AddFileRsp_FieldNumber_FileSize = 4,
  AddFileRsp_FieldNumber_FileDate = 5,
};

@interface AddFileRsp : GPBMessage

@property(nonatomic, readwrite) AddFileRsp_ResultCode resultCode;

@property(nonatomic, readwrite) BOOL hasResultCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileName;
/** Test to see if @c fileName has been set. */
@property(nonatomic, readwrite) BOOL hasFileName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileInfo;
/** Test to see if @c fileInfo has been set. */
@property(nonatomic, readwrite) BOOL hasFileInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileSize;
/** Test to see if @c fileSize has been set. */
@property(nonatomic, readwrite) BOOL hasFileSize;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileDate;
/** Test to see if @c fileDate has been set. */
@property(nonatomic, readwrite) BOOL hasFileDate;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
