// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddFriendMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "AddFriendMsg.pbobjc.h"
 #import "UserData.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - AddFriendMsgRoot

@implementation AddFriendMsgRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - AddFriendMsgRoot_FileDescriptor

static GPBFileDescriptor *AddFriendMsgRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"protocol"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - AddFriendReq

@implementation AddFriendReq

@dynamic hasFriendUserId, friendUserId;
@dynamic hasRequestType, requestType;

typedef struct AddFriendReq__storage_ {
  uint32_t _has_storage_[1];
  AddFriendReq_RequestType requestType;
  NSString *friendUserId;
} AddFriendReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "friendUserId",
        .dataTypeSpecific.className = NULL,
        .number = AddFriendReq_FieldNumber_FriendUserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(AddFriendReq__storage_, friendUserId),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "requestType",
        .dataTypeSpecific.enumDescFunc = AddFriendReq_RequestType_EnumDescriptor,
        .number = AddFriendReq_FieldNumber_RequestType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(AddFriendReq__storage_, requestType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[AddFriendReq class]
                                     rootClass:[AddFriendMsgRoot class]
                                          file:AddFriendMsgRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(AddFriendReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\014\000\002\013\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum AddFriendReq_RequestType

GPBEnumDescriptor *AddFriendReq_RequestType_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Request\000Agree\000Refuse\000";
    static const int32_t values[] = {
        AddFriendReq_RequestType_Request,
        AddFriendReq_RequestType_Agree,
        AddFriendReq_RequestType_Refuse,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(AddFriendReq_RequestType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:AddFriendReq_RequestType_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL AddFriendReq_RequestType_IsValidValue(int32_t value__) {
  switch (value__) {
    case AddFriendReq_RequestType_Request:
    case AddFriendReq_RequestType_Agree:
    case AddFriendReq_RequestType_Refuse:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - AddFriendRsp

@implementation AddFriendRsp

@dynamic hasResultCode, resultCode;
@dynamic hasUser, user;
@dynamic hasRequestType, requestType;

typedef struct AddFriendRsp__storage_ {
  uint32_t _has_storage_[1];
  AddFriendRsp_ResultCode resultCode;
  AddFriendRsp_RequestType requestType;
  UserItem *user;
} AddFriendRsp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "resultCode",
        .dataTypeSpecific.enumDescFunc = AddFriendRsp_ResultCode_EnumDescriptor,
        .number = AddFriendRsp_FieldNumber_ResultCode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(AddFriendRsp__storage_, resultCode),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "user",
        .dataTypeSpecific.className = GPBStringifySymbol(UserItem),
        .number = AddFriendRsp_FieldNumber_User,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(AddFriendRsp__storage_, user),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "requestType",
        .dataTypeSpecific.enumDescFunc = AddFriendRsp_RequestType_EnumDescriptor,
        .number = AddFriendRsp_FieldNumber_RequestType,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(AddFriendRsp__storage_, requestType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[AddFriendRsp class]
                                     rootClass:[AddFriendMsgRoot class]
                                          file:AddFriendMsgRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(AddFriendRsp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\n\000\003\013\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum AddFriendRsp_ResultCode

GPBEnumDescriptor *AddFriendRsp_ResultCode_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Success\000Fail\000";
    static const int32_t values[] = {
        AddFriendRsp_ResultCode_Success,
        AddFriendRsp_ResultCode_Fail,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(AddFriendRsp_ResultCode)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:AddFriendRsp_ResultCode_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL AddFriendRsp_ResultCode_IsValidValue(int32_t value__) {
  switch (value__) {
    case AddFriendRsp_ResultCode_Success:
    case AddFriendRsp_ResultCode_Fail:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Enum AddFriendRsp_RequestType

GPBEnumDescriptor *AddFriendRsp_RequestType_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Request\000Agree\000Refuse\000";
    static const int32_t values[] = {
        AddFriendRsp_RequestType_Request,
        AddFriendRsp_RequestType_Agree,
        AddFriendRsp_RequestType_Refuse,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(AddFriendRsp_RequestType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:AddFriendRsp_RequestType_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL AddFriendRsp_RequestType_IsValidValue(int32_t value__) {
  switch (value__) {
    case AddFriendRsp_RequestType_Request:
    case AddFriendRsp_RequestType_Agree:
    case AddFriendRsp_RequestType_Refuse:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
