// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AgreeAddFriendMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum AgreeAddFriendRsp_ResultCode

typedef GPB_ENUM(AgreeAddFriendRsp_ResultCode) {
  AgreeAddFriendRsp_ResultCode_Success = 0,
  AgreeAddFriendRsp_ResultCode_Fail = 1,
};

GPBEnumDescriptor *AgreeAddFriendRsp_ResultCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL AgreeAddFriendRsp_ResultCode_IsValidValue(int32_t value);

#pragma mark - AgreeAddFriendMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AgreeAddFriendMsgRoot : GPBRootObject
@end

#pragma mark - AgreeAddFriendReq

typedef GPB_ENUM(AgreeAddFriendReq_FieldNumber) {
  AgreeAddFriendReq_FieldNumber_FriendUserId = 1,
};

@interface AgreeAddFriendReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *friendUserId;
/** Test to see if @c friendUserId has been set. */
@property(nonatomic, readwrite) BOOL hasFriendUserId;

@end

#pragma mark - AgreeAddFriendRsp

typedef GPB_ENUM(AgreeAddFriendRsp_FieldNumber) {
  AgreeAddFriendRsp_FieldNumber_ResultCode = 1,
};

@interface AgreeAddFriendRsp : GPBMessage

@property(nonatomic, readwrite) AgreeAddFriendRsp_ResultCode resultCode;

@property(nonatomic, readwrite) BOOL hasResultCode;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
