// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChangeFriendMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UserItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ChangeFriendSync_ChangeType

typedef GPB_ENUM(ChangeFriendSync_ChangeType) {
  ChangeFriendSync_ChangeType_Add = 0,
  ChangeFriendSync_ChangeType_Delete = 1,
  ChangeFriendSync_ChangeType_Update = 2,
};

GPBEnumDescriptor *ChangeFriendSync_ChangeType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ChangeFriendSync_ChangeType_IsValidValue(int32_t value);

#pragma mark - ChangeFriendMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ChangeFriendMsgRoot : GPBRootObject
@end

#pragma mark - ChangeFriendSync

typedef GPB_ENUM(ChangeFriendSync_FieldNumber) {
  ChangeFriendSync_FieldNumber_ChangeType = 1,
  ChangeFriendSync_FieldNumber_UserItem = 2,
};

@interface ChangeFriendSync : GPBMessage

@property(nonatomic, readwrite) ChangeFriendSync_ChangeType changeType;

@property(nonatomic, readwrite) BOOL hasChangeType;
@property(nonatomic, readwrite, strong, null_resettable) UserItem *userItem;
/** Test to see if @c userItem has been set. */
@property(nonatomic, readwrite) BOOL hasUserItem;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
