// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeleteFileMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum DeleteFileRsp_ResultCode

typedef GPB_ENUM(DeleteFileRsp_ResultCode) {
  DeleteFileRsp_ResultCode_Success = 0,
  DeleteFileRsp_ResultCode_Fail = 1,
};

GPBEnumDescriptor *DeleteFileRsp_ResultCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL DeleteFileRsp_ResultCode_IsValidValue(int32_t value);

#pragma mark - DeleteFileMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DeleteFileMsgRoot : GPBRootObject
@end

#pragma mark - DeleteFileReq

typedef GPB_ENUM(DeleteFileReq_FieldNumber) {
  DeleteFileReq_FieldNumber_UserId = 1,
  DeleteFileReq_FieldNumber_FileId = 2,
  DeleteFileReq_FieldNumber_FileName = 3,
  DeleteFileReq_FieldNumber_FileSize = 4,
  DeleteFileReq_FieldNumber_FileInfo = 5,
  DeleteFileReq_FieldNumber_FileURL = 6,
  DeleteFileReq_FieldNumber_FilePwd = 7,
};

@interface DeleteFileReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;
/** Test to see if @c userId has been set. */
@property(nonatomic, readwrite) BOOL hasUserId;

@property(nonatomic, readwrite) int32_t fileId;

@property(nonatomic, readwrite) BOOL hasFileId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileName;
/** Test to see if @c fileName has been set. */
@property(nonatomic, readwrite) BOOL hasFileName;

@property(nonatomic, readwrite) int64_t fileSize;

@property(nonatomic, readwrite) BOOL hasFileSize;
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileInfo;
/** Test to see if @c fileInfo has been set. */
@property(nonatomic, readwrite) BOOL hasFileInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileURL;
/** Test to see if @c fileURL has been set. */
@property(nonatomic, readwrite) BOOL hasFileURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *filePwd;
/** Test to see if @c filePwd has been set. */
@property(nonatomic, readwrite) BOOL hasFilePwd;

@end

#pragma mark - DeleteFileRsp

typedef GPB_ENUM(DeleteFileRsp_FieldNumber) {
  DeleteFileRsp_FieldNumber_ResultCode = 1,
  DeleteFileRsp_FieldNumber_FileId = 2,
  DeleteFileRsp_FieldNumber_FileName = 3,
  DeleteFileRsp_FieldNumber_FileDate = 4,
  DeleteFileRsp_FieldNumber_FileInfo = 5,
};

@interface DeleteFileRsp : GPBMessage

@property(nonatomic, readwrite) DeleteFileRsp_ResultCode resultCode;

@property(nonatomic, readwrite) BOOL hasResultCode;
@property(nonatomic, readwrite) int32_t fileId;

@property(nonatomic, readwrite) BOOL hasFileId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileName;
/** Test to see if @c fileName has been set. */
@property(nonatomic, readwrite) BOOL hasFileName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileDate;
/** Test to see if @c fileDate has been set. */
@property(nonatomic, readwrite) BOOL hasFileDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileInfo;
/** Test to see if @c fileInfo has been set. */
@property(nonatomic, readwrite) BOOL hasFileInfo;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
