// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DownloadData.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "DownloadData.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - DownloadDataRoot

@implementation DownloadDataRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - DownloadDataRoot_FileDescriptor

static GPBFileDescriptor *DownloadDataRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"protocol"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - DownloadItem

@implementation DownloadItem

@dynamic hasSendUserId, sendUserId;
@dynamic hasReceiveUserId, receiveUserId;
@dynamic hasChatBody, chatBody;
@dynamic hasDate, date;

typedef struct DownloadItem__storage_ {
  uint32_t _has_storage_[1];
  NSString *sendUserId;
  NSString *receiveUserId;
  NSString *chatBody;
  int64_t date;
} DownloadItem__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "sendUserId",
        .dataTypeSpecific.className = NULL,
        .number = DownloadItem_FieldNumber_SendUserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(DownloadItem__storage_, sendUserId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "receiveUserId",
        .dataTypeSpecific.className = NULL,
        .number = DownloadItem_FieldNumber_ReceiveUserId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(DownloadItem__storage_, receiveUserId),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "chatBody",
        .dataTypeSpecific.className = NULL,
        .number = DownloadItem_FieldNumber_ChatBody,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(DownloadItem__storage_, chatBody),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "date",
        .dataTypeSpecific.className = NULL,
        .number = DownloadItem_FieldNumber_Date,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(DownloadItem__storage_, date),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[DownloadItem class]
                                     rootClass:[DownloadDataRoot class]
                                          file:DownloadDataRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(DownloadItem__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\002\n\000\003\r\000\005\010\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
