// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DownloadData.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DownloadDataRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DownloadDataRoot : GPBRootObject
@end

#pragma mark - DownloadItem

typedef GPB_ENUM(DownloadItem_FieldNumber) {
  DownloadItem_FieldNumber_SendUserId = 2,
  DownloadItem_FieldNumber_ReceiveUserId = 3,
  DownloadItem_FieldNumber_ChatBody = 5,
  DownloadItem_FieldNumber_Date = 6,
};

@interface DownloadItem : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sendUserId;
/** Test to see if @c sendUserId has been set. */
@property(nonatomic, readwrite) BOOL hasSendUserId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *receiveUserId;
/** Test to see if @c receiveUserId has been set. */
@property(nonatomic, readwrite) BOOL hasReceiveUserId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatBody;
/** Test to see if @c chatBody has been set. */
@property(nonatomic, readwrite) BOOL hasChatBody;

@property(nonatomic, readwrite) int64_t date;

@property(nonatomic, readwrite) BOOL hasDate;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
