// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetExeInfoMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "GetExeInfoMsg.pbobjc.h"
 #import "ApplicationData.pbobjc.h"
 #import "GameData.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GetExeInfoMsgRoot

@implementation GetExeInfoMsgRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - GetExeInfoMsgRoot_FileDescriptor

static GPBFileDescriptor *GetExeInfoMsgRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"protocol"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - GetExeInfoReq

@implementation GetExeInfoReq

@dynamic hasRequestType, requestType;

typedef struct GetExeInfoReq__storage_ {
  uint32_t _has_storage_[1];
  GetExeInfoReq_RequestType requestType;
} GetExeInfoReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "requestType",
        .dataTypeSpecific.enumDescFunc = GetExeInfoReq_RequestType_EnumDescriptor,
        .number = GetExeInfoReq_FieldNumber_RequestType,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetExeInfoReq__storage_, requestType),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetExeInfoReq class]
                                     rootClass:[GetExeInfoMsgRoot class]
                                          file:GetExeInfoMsgRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetExeInfoReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\013\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum GetExeInfoReq_RequestType

GPBEnumDescriptor *GetExeInfoReq_RequestType_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "All\000Game\000Application\000";
    static const int32_t values[] = {
        GetExeInfoReq_RequestType_All,
        GetExeInfoReq_RequestType_Game,
        GetExeInfoReq_RequestType_Application,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(GetExeInfoReq_RequestType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:GetExeInfoReq_RequestType_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL GetExeInfoReq_RequestType_IsValidValue(int32_t value__) {
  switch (value__) {
    case GetExeInfoReq_RequestType_All:
    case GetExeInfoReq_RequestType_Game:
    case GetExeInfoReq_RequestType_Application:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - GetExeInfoRsp

@implementation GetExeInfoRsp

@dynamic hasResultCode, resultCode;
@dynamic applicationItemArray, applicationItemArray_Count;
@dynamic gameItemArray, gameItemArray_Count;

typedef struct GetExeInfoRsp__storage_ {
  uint32_t _has_storage_[1];
  GetExeInfoRsp_ResultCode resultCode;
  NSMutableArray *applicationItemArray;
  NSMutableArray *gameItemArray;
} GetExeInfoRsp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "resultCode",
        .dataTypeSpecific.enumDescFunc = GetExeInfoRsp_ResultCode_EnumDescriptor,
        .number = GetExeInfoRsp_FieldNumber_ResultCode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetExeInfoRsp__storage_, resultCode),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "applicationItemArray",
        .dataTypeSpecific.className = GPBStringifySymbol(ApplicationItem),
        .number = GetExeInfoRsp_FieldNumber_ApplicationItemArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetExeInfoRsp__storage_, applicationItemArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "gameItemArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GameItem),
        .number = GetExeInfoRsp_FieldNumber_GameItemArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetExeInfoRsp__storage_, gameItemArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetExeInfoRsp class]
                                     rootClass:[GetExeInfoMsgRoot class]
                                          file:GetExeInfoMsgRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetExeInfoRsp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\001\n\000\002\000applicationItem\000\003\000gameItem\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum GetExeInfoRsp_ResultCode

GPBEnumDescriptor *GetExeInfoRsp_ResultCode_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Success\000Fail\000";
    static const int32_t values[] = {
        GetExeInfoRsp_ResultCode_Success,
        GetExeInfoRsp_ResultCode_Fail,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(GetExeInfoRsp_ResultCode)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:GetExeInfoRsp_ResultCode_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL GetExeInfoRsp_ResultCode_IsValidValue(int32_t value__) {
  switch (value__) {
    case GetExeInfoRsp_ResultCode_Success:
    case GetExeInfoRsp_ResultCode_Fail:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
