// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetFileInfoMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class FileItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum GetFileInfoRsp_ResultCode

typedef GPB_ENUM(GetFileInfoRsp_ResultCode) {
  /** 搜索到文件 */
  GetFileInfoRsp_ResultCode_Success = 0,

  /** 未搜索到文件 */
  GetFileInfoRsp_ResultCode_Fail = 1,

  /** 文件不存在 */
  GetFileInfoRsp_ResultCode_FileNotExist = 2,
};

GPBEnumDescriptor *GetFileInfoRsp_ResultCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL GetFileInfoRsp_ResultCode_IsValidValue(int32_t value);

#pragma mark - GetFileInfoMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GetFileInfoMsgRoot : GPBRootObject
@end

#pragma mark - GetFileInfoReq

typedef GPB_ENUM(GetFileInfoReq_FieldNumber) {
  GetFileInfoReq_FieldNumber_FileId = 1,
};

@interface GetFileInfoReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;
/** Test to see if @c fileId has been set. */
@property(nonatomic, readwrite) BOOL hasFileId;

@end

#pragma mark - GetFileInfoRsp

typedef GPB_ENUM(GetFileInfoRsp_FieldNumber) {
  GetFileInfoRsp_FieldNumber_ResultCode = 1,
  GetFileInfoRsp_FieldNumber_FileItem = 2,
};

@interface GetFileInfoRsp : GPBMessage

@property(nonatomic, readwrite) GetFileInfoRsp_ResultCode resultCode;

@property(nonatomic, readwrite) BOOL hasResultCode;
@property(nonatomic, readwrite, strong, null_resettable) FileItem *fileItem;
/** Test to see if @c fileItem has been set. */
@property(nonatomic, readwrite) BOOL hasFileItem;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
