// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetGroupInfoMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class FileItem;
@class GroupItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum GetGroupInfoRsp_ResultCode

typedef GPB_ENUM(GetGroupInfoRsp_ResultCode) {
  /** 搜索到群 */
  GetGroupInfoRsp_ResultCode_Success = 0,

  /** 未搜索到群 */
  GetGroupInfoRsp_ResultCode_Fail = 1,

  /** 群不存在 */
  GetGroupInfoRsp_ResultCode_GroupNotExist = 2,
};

GPBEnumDescriptor *GetGroupInfoRsp_ResultCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL GetGroupInfoRsp_ResultCode_IsValidValue(int32_t value);

#pragma mark - GetGroupInfoMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GetGroupInfoMsgRoot : GPBRootObject
@end

#pragma mark - GetGroupInfoReq

typedef GPB_ENUM(GetGroupInfoReq_FieldNumber) {
  GetGroupInfoReq_FieldNumber_GroupId = 1,
  GetGroupInfoReq_FieldNumber_Where = 2,
  GetGroupInfoReq_FieldNumber_FileInfo = 3,
};

@interface GetGroupInfoReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;
/** Test to see if @c groupId has been set. */
@property(nonatomic, readwrite) BOOL hasGroupId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *where;
/** Test to see if @c where has been set. */
@property(nonatomic, readwrite) BOOL hasWhere;

@property(nonatomic, readwrite) BOOL fileInfo;

@property(nonatomic, readwrite) BOOL hasFileInfo;
@end

#pragma mark - GetGroupInfoRsp

typedef GPB_ENUM(GetGroupInfoRsp_FieldNumber) {
  GetGroupInfoRsp_FieldNumber_ResultCode = 1,
  GetGroupInfoRsp_FieldNumber_GroupItem = 2,
  GetGroupInfoRsp_FieldNumber_Where = 3,
  GetGroupInfoRsp_FieldNumber_FilesArray = 4,
};

@interface GetGroupInfoRsp : GPBMessage

@property(nonatomic, readwrite) GetGroupInfoRsp_ResultCode resultCode;

@property(nonatomic, readwrite) BOOL hasResultCode;
@property(nonatomic, readwrite, strong, null_resettable) GroupItem *groupItem;
/** Test to see if @c groupItem has been set. */
@property(nonatomic, readwrite) BOOL hasGroupItem;

@property(nonatomic, readwrite, copy, null_resettable) NSString *where;
/** Test to see if @c where has been set. */
@property(nonatomic, readwrite) BOOL hasWhere;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FileItem*> *filesArray;
/** The number of items in @c filesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger filesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
