// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetMiracastInfoMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MiracastItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum GetMiracastRsp_ResultCode

typedef GPB_ENUM(GetMiracastRsp_ResultCode) {
  /** 搜索到miracast */
  GetMiracastRsp_ResultCode_Success = 0,

  /** 未搜索到miracast */
  GetMiracastRsp_ResultCode_Fail = 1,

  /** miracast不存在 */
  GetMiracastRsp_ResultCode_MiracastNotExist = 2,
};

GPBEnumDescriptor *GetMiracastRsp_ResultCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL GetMiracastRsp_ResultCode_IsValidValue(int32_t value);

#pragma mark - GetMiracastInfoMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GetMiracastInfoMsgRoot : GPBRootObject
@end

#pragma mark - GetMiracastReq

typedef GPB_ENUM(GetMiracastReq_FieldNumber) {
  GetMiracastReq_FieldNumber_Model = 1,
};

@interface GetMiracastReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *model;
/** Test to see if @c model has been set. */
@property(nonatomic, readwrite) BOOL hasModel;

@end

#pragma mark - GetMiracastRsp

typedef GPB_ENUM(GetMiracastRsp_FieldNumber) {
  GetMiracastRsp_FieldNumber_ResultCode = 1,
  GetMiracastRsp_FieldNumber_MiracastItem = 2,
};

@interface GetMiracastRsp : GPBMessage

@property(nonatomic, readwrite) GetMiracastRsp_ResultCode resultCode;

@property(nonatomic, readwrite) BOOL hasResultCode;
@property(nonatomic, readwrite, strong, null_resettable) MiracastItem *miracastItem;
/** Test to see if @c miracastItem has been set. */
@property(nonatomic, readwrite) BOOL hasMiracastItem;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
