// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetPersonalInfoMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "GetPersonalInfoMsg.pbobjc.h"
 #import "UserData.pbobjc.h"
 #import "GroupData.pbobjc.h"
 #import "FileData.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GetPersonalInfoMsgRoot

@implementation GetPersonalInfoMsgRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - GetPersonalInfoMsgRoot_FileDescriptor

static GPBFileDescriptor *GetPersonalInfoMsgRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"protocol"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - GetPersonalInfoReq

@implementation GetPersonalInfoReq

@dynamic hasUserId, userId;
@dynamic hasWhere, where;
@dynamic hasUserInfo, userInfo;
@dynamic hasFriendInfo, friendInfo;
@dynamic hasFileInfo, fileInfo;
@dynamic hasGroupInfo, groupInfo;

typedef struct GetPersonalInfoReq__storage_ {
  uint32_t _has_storage_[1];
  NSString *userId;
  NSString *where;
} GetPersonalInfoReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = GetPersonalInfoReq_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetPersonalInfoReq__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "where",
        .dataTypeSpecific.className = NULL,
        .number = GetPersonalInfoReq_FieldNumber_Where,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetPersonalInfoReq__storage_, where),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userInfo",
        .dataTypeSpecific.className = NULL,
        .number = GetPersonalInfoReq_FieldNumber_UserInfo,
        .hasIndex = 2,
        .offset = 3,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasDefaultValue | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "friendInfo",
        .dataTypeSpecific.className = NULL,
        .number = GetPersonalInfoReq_FieldNumber_FriendInfo,
        .hasIndex = 4,
        .offset = 5,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasDefaultValue | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "fileInfo",
        .dataTypeSpecific.className = NULL,
        .number = GetPersonalInfoReq_FieldNumber_FileInfo,
        .hasIndex = 6,
        .offset = 7,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasDefaultValue | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "groupInfo",
        .dataTypeSpecific.className = NULL,
        .number = GetPersonalInfoReq_FieldNumber_GroupInfo,
        .hasIndex = 8,
        .offset = 9,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasDefaultValue | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetPersonalInfoReq class]
                                     rootClass:[GetPersonalInfoMsgRoot class]
                                          file:GetPersonalInfoMsgRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetPersonalInfoReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\005\001\006\000\003\010\000\004\n\000\005\010\000\006\t\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetPersonalInfoRsp

@implementation GetPersonalInfoRsp

@dynamic hasResultCode, resultCode;
@dynamic hasWhere, where;
@dynamic hasUserInfo, userInfo;
@dynamic friendsArray, friendsArray_Count;
@dynamic filesArray, filesArray_Count;
@dynamic groupsArray, groupsArray_Count;

typedef struct GetPersonalInfoRsp__storage_ {
  uint32_t _has_storage_[1];
  GetPersonalInfoRsp_ResultCode resultCode;
  NSString *where;
  UserItem *userInfo;
  NSMutableArray *friendsArray;
  NSMutableArray *filesArray;
  NSMutableArray *groupsArray;
} GetPersonalInfoRsp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "resultCode",
        .dataTypeSpecific.enumDescFunc = GetPersonalInfoRsp_ResultCode_EnumDescriptor,
        .number = GetPersonalInfoRsp_FieldNumber_ResultCode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetPersonalInfoRsp__storage_, resultCode),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "where",
        .dataTypeSpecific.className = NULL,
        .number = GetPersonalInfoRsp_FieldNumber_Where,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetPersonalInfoRsp__storage_, where),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userInfo",
        .dataTypeSpecific.className = GPBStringifySymbol(UserItem),
        .number = GetPersonalInfoRsp_FieldNumber_UserInfo,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GetPersonalInfoRsp__storage_, userInfo),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "friendsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(UserItem),
        .number = GetPersonalInfoRsp_FieldNumber_FriendsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetPersonalInfoRsp__storage_, friendsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "filesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(FileItem),
        .number = GetPersonalInfoRsp_FieldNumber_FilesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetPersonalInfoRsp__storage_, filesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "groupsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GroupItem),
        .number = GetPersonalInfoRsp_FieldNumber_GroupsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetPersonalInfoRsp__storage_, groupsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetPersonalInfoRsp class]
                                     rootClass:[GetPersonalInfoMsgRoot class]
                                          file:GetPersonalInfoMsgRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetPersonalInfoRsp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\n\000\003\010\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum GetPersonalInfoRsp_ResultCode

GPBEnumDescriptor *GetPersonalInfoRsp_ResultCode_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Success\000Fail\000";
    static const int32_t values[] = {
        GetPersonalInfoRsp_ResultCode_Success,
        GetPersonalInfoRsp_ResultCode_Fail,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(GetPersonalInfoRsp_ResultCode)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:GetPersonalInfoRsp_ResultCode_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL GetPersonalInfoRsp_ResultCode_IsValidValue(int32_t value__) {
  switch (value__) {
    case GetPersonalInfoRsp_ResultCode_Success:
    case GetPersonalInfoRsp_ResultCode_Fail:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
