// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetPersonalInfoMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class FileItemForMedia;
@class GroupItem;
@class UserItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum GetPersonalInfoRsp_ResultCode

typedef GPB_ENUM(GetPersonalInfoRsp_ResultCode) {
  /** 搜索到用户 */
  GetPersonalInfoRsp_ResultCode_Success = 0,

  /** 未搜索到用户 */
  GetPersonalInfoRsp_ResultCode_Fail = 1,
};

GPBEnumDescriptor *GetPersonalInfoRsp_ResultCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL GetPersonalInfoRsp_ResultCode_IsValidValue(int32_t value);

#pragma mark - GetPersonalInfoMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GetPersonalInfoMsgRoot : GPBRootObject
@end

#pragma mark - GetPersonalInfoReq

typedef GPB_ENUM(GetPersonalInfoReq_FieldNumber) {
  GetPersonalInfoReq_FieldNumber_UserId = 1,
  GetPersonalInfoReq_FieldNumber_Where = 2,
  GetPersonalInfoReq_FieldNumber_UserInfo = 3,
  GetPersonalInfoReq_FieldNumber_FriendInfo = 4,
  GetPersonalInfoReq_FieldNumber_FileInfo = 5,
  GetPersonalInfoReq_FieldNumber_GroupInfo = 6,
};

@interface GetPersonalInfoReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;
/** Test to see if @c userId has been set. */
@property(nonatomic, readwrite) BOOL hasUserId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *where;
/** Test to see if @c where has been set. */
@property(nonatomic, readwrite) BOOL hasWhere;

@property(nonatomic, readwrite) BOOL userInfo;

@property(nonatomic, readwrite) BOOL hasUserInfo;
@property(nonatomic, readwrite) BOOL friendInfo;

@property(nonatomic, readwrite) BOOL hasFriendInfo;
@property(nonatomic, readwrite) BOOL fileInfo;

@property(nonatomic, readwrite) BOOL hasFileInfo;
@property(nonatomic, readwrite) BOOL groupInfo;

@property(nonatomic, readwrite) BOOL hasGroupInfo;
@end

#pragma mark - GetPersonalInfoRsp

typedef GPB_ENUM(GetPersonalInfoRsp_FieldNumber) {
  GetPersonalInfoRsp_FieldNumber_ResultCode = 1,
  GetPersonalInfoRsp_FieldNumber_Where = 2,
  GetPersonalInfoRsp_FieldNumber_UserInfo = 3,
  GetPersonalInfoRsp_FieldNumber_FriendsArray = 4,
  GetPersonalInfoRsp_FieldNumber_FilesArray = 5,
  GetPersonalInfoRsp_FieldNumber_GroupsArray = 6,
};

@interface GetPersonalInfoRsp : GPBMessage

@property(nonatomic, readwrite) GetPersonalInfoRsp_ResultCode resultCode;

@property(nonatomic, readwrite) BOOL hasResultCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *where;
/** Test to see if @c where has been set. */
@property(nonatomic, readwrite) BOOL hasWhere;

@property(nonatomic, readwrite, strong, null_resettable) UserItem *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserItem*> *friendsArray;
/** The number of items in @c friendsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger friendsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FileItemForMedia*> *filesArray;
/** The number of items in @c filesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger filesArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GroupItem*> *groupsArray;
/** The number of items in @c groupsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
