// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetUserInfoMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class FileItemForMedia;
@class UserItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum GetUserInfoRsp_ResultCode

typedef GPB_ENUM(GetUserInfoRsp_ResultCode) {
  /** 搜索到用户 */
  GetUserInfoRsp_ResultCode_Success = 0,

  /** 未搜索到用户 */
  GetUserInfoRsp_ResultCode_Fail = 1,

  /** 用户不存在 */
  GetUserInfoRsp_ResultCode_UserNotExist = 2,
};

GPBEnumDescriptor *GetUserInfoRsp_ResultCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL GetUserInfoRsp_ResultCode_IsValidValue(int32_t value);

#pragma mark - GetUserInfoMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GetUserInfoMsgRoot : GPBRootObject
@end

#pragma mark - GetUserInfoReq

typedef GPB_ENUM(GetUserInfoReq_FieldNumber) {
  GetUserInfoReq_FieldNumber_TargetUserIdArray = 1,
  GetUserInfoReq_FieldNumber_FileInfo = 2,
};

@interface GetUserInfoReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *targetUserIdArray;
/** The number of items in @c targetUserIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger targetUserIdArray_Count;

@property(nonatomic, readwrite) BOOL fileInfo;

@property(nonatomic, readwrite) BOOL hasFileInfo;
@end

#pragma mark - GetUserInfoRsp

typedef GPB_ENUM(GetUserInfoRsp_FieldNumber) {
  GetUserInfoRsp_FieldNumber_ResultCode = 1,
  GetUserInfoRsp_FieldNumber_UserItemArray = 2,
  GetUserInfoRsp_FieldNumber_FilesArray = 3,
};

@interface GetUserInfoRsp : GPBMessage

@property(nonatomic, readwrite) GetUserInfoRsp_ResultCode resultCode;

@property(nonatomic, readwrite) BOOL hasResultCode;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserItem*> *userItemArray;
/** The number of items in @c userItemArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userItemArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FileItemForMedia*> *filesArray;
/** The number of items in @c filesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger filesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
