// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetUserInfoMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "GetUserInfoMsg.pbobjc.h"
 #import "UserData.pbobjc.h"
 #import "FileData.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GetUserInfoMsgRoot

@implementation GetUserInfoMsgRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - GetUserInfoMsgRoot_FileDescriptor

static GPBFileDescriptor *GetUserInfoMsgRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"protocol"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - GetUserInfoReq

@implementation GetUserInfoReq

@dynamic targetUserIdArray, targetUserIdArray_Count;
@dynamic hasFileInfo, fileInfo;

typedef struct GetUserInfoReq__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *targetUserIdArray;
} GetUserInfoReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "targetUserIdArray",
        .dataTypeSpecific.className = NULL,
        .number = GetUserInfoReq_FieldNumber_TargetUserIdArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetUserInfoReq__storage_, targetUserIdArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fileInfo",
        .dataTypeSpecific.className = NULL,
        .number = GetUserInfoReq_FieldNumber_FileInfo,
        .hasIndex = 0,
        .offset = 1,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasDefaultValue | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetUserInfoReq class]
                                     rootClass:[GetUserInfoMsgRoot class]
                                          file:GetUserInfoMsgRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetUserInfoReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\000targetUserId\000\002\010\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetUserInfoRsp

@implementation GetUserInfoRsp

@dynamic hasResultCode, resultCode;
@dynamic userItemArray, userItemArray_Count;
@dynamic filesArray, filesArray_Count;

typedef struct GetUserInfoRsp__storage_ {
  uint32_t _has_storage_[1];
  GetUserInfoRsp_ResultCode resultCode;
  NSMutableArray *userItemArray;
  NSMutableArray *filesArray;
} GetUserInfoRsp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "resultCode",
        .dataTypeSpecific.enumDescFunc = GetUserInfoRsp_ResultCode_EnumDescriptor,
        .number = GetUserInfoRsp_FieldNumber_ResultCode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetUserInfoRsp__storage_, resultCode),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "userItemArray",
        .dataTypeSpecific.className = GPBStringifySymbol(UserItem),
        .number = GetUserInfoRsp_FieldNumber_UserItemArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetUserInfoRsp__storage_, userItemArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "filesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(FileItem),
        .number = GetUserInfoRsp_FieldNumber_FilesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetUserInfoRsp__storage_, filesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetUserInfoRsp class]
                                     rootClass:[GetUserInfoMsgRoot class]
                                          file:GetUserInfoMsgRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetUserInfoRsp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\n\000\002\000userItem\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum GetUserInfoRsp_ResultCode

GPBEnumDescriptor *GetUserInfoRsp_ResultCode_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Success\000Fail\000UserNotExist\000";
    static const int32_t values[] = {
        GetUserInfoRsp_ResultCode_Success,
        GetUserInfoRsp_ResultCode_Fail,
        GetUserInfoRsp_ResultCode_UserNotExist,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(GetUserInfoRsp_ResultCode)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:GetUserInfoRsp_ResultCode_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL GetUserInfoRsp_ResultCode_IsValidValue(int32_t value__) {
  switch (value__) {
    case GetUserInfoRsp_ResultCode_Success:
    case GetUserInfoRsp_ResultCode_Fail:
    case GetUserInfoRsp_ResultCode_UserNotExist:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
