// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupData.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GroupDataRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GroupDataRoot : GPBRootObject
@end

#pragma mark - GroupItem

typedef GPB_ENUM(GroupItem_FieldNumber) {
  GroupItem_FieldNumber_GroupId = 1,
  GroupItem_FieldNumber_GroupName = 2,
  GroupItem_FieldNumber_CreaterUserId = 3,
  GroupItem_FieldNumber_MemberUserIdArray = 4,
};

@interface GroupItem : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;
/** Test to see if @c groupId has been set. */
@property(nonatomic, readwrite) BOOL hasGroupId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;
/** Test to see if @c groupName has been set. */
@property(nonatomic, readwrite) BOOL hasGroupName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *createrUserId;
/** Test to see if @c createrUserId has been set. */
@property(nonatomic, readwrite) BOOL hasCreaterUserId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *memberUserIdArray;
/** The number of items in @c memberUserIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger memberUserIdArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
