// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeepAliveMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "KeepAliveMsg.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - KeepAliveMsgRoot

@implementation KeepAliveMsgRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - KeepAliveMsgRoot_FileDescriptor

static GPBFileDescriptor *KeepAliveMsgRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"protocol"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - KeepAliveSyncPacket

@implementation KeepAliveSyncPacket

@dynamic hasA, a;
@dynamic hasB, b;
@dynamic hasC, c;
@dynamic hasClientsId, clientsId;

typedef struct KeepAliveSyncPacket__storage_ {
  uint32_t _has_storage_[1];
  int32_t a;
  NSString *c;
  NSString *clientsId;
} KeepAliveSyncPacket__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "a",
        .dataTypeSpecific.className = NULL,
        .number = KeepAliveSyncPacket_FieldNumber_A,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(KeepAliveSyncPacket__storage_, a),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "b",
        .dataTypeSpecific.className = NULL,
        .number = KeepAliveSyncPacket_FieldNumber_B,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "c",
        .dataTypeSpecific.className = NULL,
        .number = KeepAliveSyncPacket_FieldNumber_C,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(KeepAliveSyncPacket__storage_, c),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "clientsId",
        .dataTypeSpecific.className = NULL,
        .number = KeepAliveSyncPacket_FieldNumber_ClientsId,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(KeepAliveSyncPacket__storage_, clientsId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[KeepAliveSyncPacket class]
                                     rootClass:[KeepAliveMsgRoot class]
                                          file:KeepAliveMsgRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(KeepAliveSyncPacket__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\004\t\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
