// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeepAliveMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - KeepAliveMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface KeepAliveMsgRoot : GPBRootObject
@end

#pragma mark - KeepAliveSyncPacket

typedef GPB_ENUM(KeepAliveSyncPacket_FieldNumber) {
  KeepAliveSyncPacket_FieldNumber_A = 1,
  KeepAliveSyncPacket_FieldNumber_B = 2,
  KeepAliveSyncPacket_FieldNumber_C = 3,
  KeepAliveSyncPacket_FieldNumber_ClientsId = 4,
};

@interface KeepAliveSyncPacket : GPBMessage

@property(nonatomic, readwrite) int32_t a;

@property(nonatomic, readwrite) BOOL hasA;
@property(nonatomic, readwrite) BOOL b;

@property(nonatomic, readwrite) BOOL hasB;
@property(nonatomic, readwrite, copy, null_resettable) NSString *c;
/** Test to see if @c c has been set. */
@property(nonatomic, readwrite) BOOL hasC;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientsId;
/** Test to see if @c clientsId has been set. */
@property(nonatomic, readwrite) BOOL hasClientsId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
