// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MiracastData.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MiracastDataRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MiracastDataRoot : GPBRootObject
@end

#pragma mark - MiracastItem

typedef GPB_ENUM(MiracastItem_FieldNumber) {
  MiracastItem_FieldNumber_Manufactory = 1,
  MiracastItem_FieldNumber_Appname = 2,
  MiracastItem_FieldNumber_Packagename = 3,
  MiracastItem_FieldNumber_Model = 4,
};

@interface MiracastItem : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *manufactory;
/** Test to see if @c manufactory has been set. */
@property(nonatomic, readwrite) BOOL hasManufactory;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appname;
/** Test to see if @c appname has been set. */
@property(nonatomic, readwrite) BOOL hasAppname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *packagename;
/** Test to see if @c packagename has been set. */
@property(nonatomic, readwrite) BOOL hasPackagename;

@property(nonatomic, readwrite, copy, null_resettable) NSString *model;
/** Test to see if @c model has been set. */
@property(nonatomic, readwrite) BOOL hasModel;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
