// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OffLineMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum OffLineSync_CauseCode

/** 下线原因 */
typedef GPB_ENUM(OffLineSync_CauseCode) {
  /** 修改密码 */
  OffLineSync_CauseCode_ChangePassword = 0,

  /** 其他设备登录 */
  OffLineSync_CauseCode_AnotherLogin = 1,
  OffLineSync_CauseCode_KeepAliveFalse = 2,
};

GPBEnumDescriptor *OffLineSync_CauseCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OffLineSync_CauseCode_IsValidValue(int32_t value);

#pragma mark - OffLineMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface OffLineMsgRoot : GPBRootObject
@end

#pragma mark - OffLineSync

typedef GPB_ENUM(OffLineSync_FieldNumber) {
  OffLineSync_FieldNumber_CauseCode = 1,
};

@interface OffLineSync : GPBMessage

@property(nonatomic, readwrite) OffLineSync_CauseCode causeCode;

@property(nonatomic, readwrite) BOOL hasCauseCode;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
