// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PersonalSettingsMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PersonalSettingsRsp_ResultCode

typedef GPB_ENUM(PersonalSettingsRsp_ResultCode) {
  PersonalSettingsRsp_ResultCode_Success = 0,
  PersonalSettingsRsp_ResultCode_Fail = 1,
  PersonalSettingsRsp_ResultCode_Oldpasswordwrong = 2,

  /** 验证码错误 */
  PersonalSettingsRsp_ResultCode_Codewrong = 3,
};

GPBEnumDescriptor *PersonalSettingsRsp_ResultCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PersonalSettingsRsp_ResultCode_IsValidValue(int32_t value);

#pragma mark - Enum PersonalSettingsRsp_ChangeType

typedef GPB_ENUM(PersonalSettingsRsp_ChangeType) {
  PersonalSettingsRsp_ChangeType_Name = 0,
  PersonalSettingsRsp_ChangeType_Password = 1,
  PersonalSettingsRsp_ChangeType_Address = 2,
  PersonalSettingsRsp_ChangeType_Mainmac = 3,
};

GPBEnumDescriptor *PersonalSettingsRsp_ChangeType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PersonalSettingsRsp_ChangeType_IsValidValue(int32_t value);

#pragma mark - PersonalSettingsMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PersonalSettingsMsgRoot : GPBRootObject
@end

#pragma mark - PersonalSettingsReq

typedef GPB_ENUM(PersonalSettingsReq_FieldNumber) {
  PersonalSettingsReq_FieldNumber_UserName = 1,
  PersonalSettingsReq_FieldNumber_UserPassword = 2,
  PersonalSettingsReq_FieldNumber_HeadIndex = 3,
  PersonalSettingsReq_FieldNumber_Code = 4,
  PersonalSettingsReq_FieldNumber_UserOldPassword = 5,
  PersonalSettingsReq_FieldNumber_UserAddress = 6,
  PersonalSettingsReq_FieldNumber_UserStreet = 7,
  PersonalSettingsReq_FieldNumber_UserCommunity = 8,
  PersonalSettingsReq_FieldNumber_UserMainMac = 9,
  PersonalSettingsReq_FieldNumber_UserId = 10,
};

@interface PersonalSettingsReq : GPBMessage

/** 呢称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userPassword;
/** Test to see if @c userPassword has been set. */
@property(nonatomic, readwrite) BOOL hasUserPassword;

@property(nonatomic, readwrite) int32_t headIndex;

@property(nonatomic, readwrite) BOOL hasHeadIndex;
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *userOldPassword;
/** Test to see if @c userOldPassword has been set. */
@property(nonatomic, readwrite) BOOL hasUserOldPassword;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userAddress;
/** Test to see if @c userAddress has been set. */
@property(nonatomic, readwrite) BOOL hasUserAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userStreet;
/** Test to see if @c userStreet has been set. */
@property(nonatomic, readwrite) BOOL hasUserStreet;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userCommunity;
/** Test to see if @c userCommunity has been set. */
@property(nonatomic, readwrite) BOOL hasUserCommunity;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userMainMac;
/** Test to see if @c userMainMac has been set. */
@property(nonatomic, readwrite) BOOL hasUserMainMac;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;
/** Test to see if @c userId has been set. */
@property(nonatomic, readwrite) BOOL hasUserId;

@end

#pragma mark - PersonalSettingsRsp

typedef GPB_ENUM(PersonalSettingsRsp_FieldNumber) {
  PersonalSettingsRsp_FieldNumber_ResultCode = 1,
  PersonalSettingsRsp_FieldNumber_ChangeType = 2,
};

@interface PersonalSettingsRsp : GPBMessage

@property(nonatomic, readwrite) PersonalSettingsRsp_ResultCode resultCode;

@property(nonatomic, readwrite) BOOL hasResultCode;
@property(nonatomic, readwrite) PersonalSettingsRsp_ChangeType changeType;

@property(nonatomic, readwrite) BOOL hasChangeType;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
