// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoHead.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ENetworkMessage

typedef GPB_ENUM(ENetworkMessage) {
  ENetworkMessage_KeepAliveSync = 0,
  ENetworkMessage_RegisterReq = 1,
  ENetworkMessage_RegisterRsp = 2,
  ENetworkMessage_LoginReq = 3,
  ENetworkMessage_LoginRsp = 4,
  ENetworkMessage_PersonalsettingsReq = 5,
  ENetworkMessage_PersonalsettingsRsp = 6,
  ENetworkMessage_GetUserinfoReq = 7,
  ENetworkMessage_GetUserinfoRsp = 8,
  ENetworkMessage_AddFriendReq = 9,
  ENetworkMessage_AddFriendRsp = 10,
  ENetworkMessage_DeleteFriendReq = 11,
  ENetworkMessage_DeleteFriendRsp = 12,
  ENetworkMessage_OfflineSync = 13,
  ENetworkMessage_LogoutReq = 14,
  ENetworkMessage_LogoutRsp = 15,
  ENetworkMessage_GetPersonalinfoReq = 16,
  ENetworkMessage_GetPersonalinfoRsp = 17,
  ENetworkMessage_ChangeFriendSync = 18,
  ENetworkMessage_SendChatReq = 19,
  ENetworkMessage_SendChatRsp = 20,
  ENetworkMessage_ReceiveChatSync = 21,
  ENetworkMessage_CreateGroupChatReq = 22,
  ENetworkMessage_CreateGroupChatRsp = 23,
  ENetworkMessage_ChangeGroupReq = 24,
  ENetworkMessage_ChangeGroupRsp = 25,
  ENetworkMessage_ChangeGroupSync = 26,
  ENetworkMessage_GetGroupInfoReq = 27,
  ENetworkMessage_GetGroupInfoRsp = 28,
  ENetworkMessage_GetFileInfoReq = 29,
  ENetworkMessage_GetFileInfoRsp = 30,
  ENetworkMessage_AddFileReq = 31,
  ENetworkMessage_AddFileRsp = 32,
  ENetworkMessage_DeleteFileReq = 33,
  ENetworkMessage_DeleteFileRsp = 34,
  ENetworkMessage_ChangeFileReq = 35,
  ENetworkMessage_ChangeFileRsp = 36,
  ENetworkMessage_GetMiracastInfoReq = 37,
  ENetworkMessage_GetMiracastInfoRsp = 38,
  ENetworkMessage_AccreditReq = 39,
  ENetworkMessage_AccreditRsp = 40,
  ENetworkMessage_GetExeInfoReq = 41,
  ENetworkMessage_GetExeInfoRsp = 42,
  ENetworkMessage_GetDownloadFileInfoReq = 43,
  ENetworkMessage_GetDownloadFileInfoRsp = 44,
  ENetworkMessage_SendCode = 45,
};

GPBEnumDescriptor *ENetworkMessage_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ENetworkMessage_IsValidValue(int32_t value);

#pragma mark - ProtoHeadRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ProtoHeadRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
