// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendCode.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum SendCodeSync_ChangeType

typedef GPB_ENUM(SendCodeSync_ChangeType) {
  /** 修改密码验证码 */
  SendCodeSync_ChangeType_Password = 0,

  /** 注册验证码 */
  SendCodeSync_ChangeType_Register = 1,

  /** 未知 */
  SendCodeSync_ChangeType_Mobile = 2,

  /** 使用验证码登录验证码 */
  SendCodeSync_ChangeType_Login = 3,

  /** 修改主设备 */
  SendCodeSync_ChangeType_Mainphone = 4,
};

GPBEnumDescriptor *SendCodeSync_ChangeType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SendCodeSync_ChangeType_IsValidValue(int32_t value);

#pragma mark - SendCodeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SendCodeRoot : GPBRootObject
@end

#pragma mark - SendCodeSync

typedef GPB_ENUM(SendCodeSync_FieldNumber) {
  SendCodeSync_FieldNumber_ChangeType = 1,
  SendCodeSync_FieldNumber_Mobile = 2,
  SendCodeSync_FieldNumber_UserId = 3,
};

/**
 * *
 * 胡国勇 3.28修改
 * 其中MOBILE字段是上一届遗留下来的不知道有没有用处
 * 没做改动
 **/
@interface SendCodeSync : GPBMessage

@property(nonatomic, readwrite) SendCodeSync_ChangeType changeType;

@property(nonatomic, readwrite) BOOL hasChangeType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *mobile;
/** Test to see if @c mobile has been set. */
@property(nonatomic, readwrite) BOOL hasMobile;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;
/** Test to see if @c userId has been set. */
@property(nonatomic, readwrite) BOOL hasUserId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
