// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendDownloadMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DownloadItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum SendDownloadRsp_ResultCode

typedef GPB_ENUM(SendDownloadRsp_ResultCode) {
  SendDownloadRsp_ResultCode_Success = 0,
  SendDownloadRsp_ResultCode_Fail = 1,
};

GPBEnumDescriptor *SendDownloadRsp_ResultCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SendDownloadRsp_ResultCode_IsValidValue(int32_t value);

#pragma mark - SendDownloadMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SendDownloadMsgRoot : GPBRootObject
@end

#pragma mark - SendDownloadReq

typedef GPB_ENUM(SendDownloadReq_FieldNumber) {
  SendDownloadReq_FieldNumber_DownloadData = 1,
};

@interface SendDownloadReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) DownloadItem *downloadData;
/** Test to see if @c downloadData has been set. */
@property(nonatomic, readwrite) BOOL hasDownloadData;

@end

#pragma mark - SendDownloadRsp

typedef GPB_ENUM(SendDownloadRsp_FieldNumber) {
  SendDownloadRsp_FieldNumber_ResultCode = 1,
};

@interface SendDownloadRsp : GPBMessage

@property(nonatomic, readwrite) SendDownloadRsp_ResultCode resultCode;

@property(nonatomic, readwrite) BOOL hasResultCode;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
