// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendChatMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ChatItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum SendChatRsp_ResultCode

typedef GPB_ENUM(SendChatRsp_ResultCode) {
  SendChatRsp_ResultCode_Success = 0,
  SendChatRsp_ResultCode_Fail = 1,
};

GPBEnumDescriptor *SendChatRsp_ResultCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SendChatRsp_ResultCode_IsValidValue(int32_t value);

#pragma mark - SendChatMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SendChatMsgRoot : GPBRootObject
@end

#pragma mark - SendChatReq

typedef GPB_ENUM(SendChatReq_FieldNumber) {
  SendChatReq_FieldNumber_ChatData = 1,
  SendChatReq_FieldNumber_Where = 2,
};

@interface SendChatReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ChatItem *chatData;
/** Test to see if @c chatData has been set. */
@property(nonatomic, readwrite) BOOL hasChatData;

@property(nonatomic, readwrite, copy, null_resettable) NSString *where;
/** Test to see if @c where has been set. */
@property(nonatomic, readwrite) BOOL hasWhere;

@end

#pragma mark - SendChatRsp

typedef GPB_ENUM(SendChatRsp_FieldNumber) {
  SendChatRsp_FieldNumber_ResultCode = 1,
  SendChatRsp_FieldNumber_ChatId = 2,
  SendChatRsp_FieldNumber_Date = 3,
  SendChatRsp_FieldNumber_Where = 4,
  SendChatRsp_FieldNumber_FileDate = 5,
  SendChatRsp_FieldNumber_PeerId = 6,
};

@interface SendChatRsp : GPBMessage

@property(nonatomic, readwrite) SendChatRsp_ResultCode resultCode;

@property(nonatomic, readwrite) BOOL hasResultCode;
@property(nonatomic, readwrite) int64_t chatId;

@property(nonatomic, readwrite) BOOL hasChatId;
@property(nonatomic, readwrite) int64_t date;

@property(nonatomic, readwrite) BOOL hasDate;
@property(nonatomic, readwrite, copy, null_resettable) NSString *where;
/** Test to see if @c where has been set. */
@property(nonatomic, readwrite) BOOL hasWhere;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileDate;
/** Test to see if @c fileDate has been set. */
@property(nonatomic, readwrite) BOOL hasFileDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *peerId;
/** Test to see if @c peerId has been set. */
@property(nonatomic, readwrite) BOOL hasPeerId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
