// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendCode.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "SendCode.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - SendCodeRoot

@implementation SendCodeRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - SendCodeRoot_FileDescriptor

static GPBFileDescriptor *SendCodeRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"protocol"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - SendCodeSync

@implementation SendCodeSync

@dynamic hasChangeType, changeType;
@dynamic hasMobile, mobile;
@dynamic hasUserId, userId;

typedef struct SendCodeSync__storage_ {
  uint32_t _has_storage_[1];
  SendCodeSync_ChangeType changeType;
  NSString *mobile;
  NSString *userId;
} SendCodeSync__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "changeType",
        .dataTypeSpecific.enumDescFunc = SendCodeSync_ChangeType_EnumDescriptor,
        .number = SendCodeSync_FieldNumber_ChangeType,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(SendCodeSync__storage_, changeType),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "mobile",
        .dataTypeSpecific.className = NULL,
        .number = SendCodeSync_FieldNumber_Mobile,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(SendCodeSync__storage_, mobile),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = SendCodeSync_FieldNumber_UserId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(SendCodeSync__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SendCodeSync class]
                                     rootClass:[SendCodeRoot class]
                                          file:SendCodeRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SendCodeSync__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\n\000\003\006\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum SendCodeSync_ChangeType

GPBEnumDescriptor *SendCodeSync_ChangeType_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Password\000Register\000Mobile\000Login\000Mainphone"
        "\000";
    static const int32_t values[] = {
        SendCodeSync_ChangeType_Password,
        SendCodeSync_ChangeType_Register,
        SendCodeSync_ChangeType_Mobile,
        SendCodeSync_ChangeType_Login,
        SendCodeSync_ChangeType_Mainphone,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(SendCodeSync_ChangeType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:SendCodeSync_ChangeType_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL SendCodeSync_ChangeType_IsValidValue(int32_t value__) {
  switch (value__) {
    case SendCodeSync_ChangeType_Password:
    case SendCodeSync_ChangeType_Register:
    case SendCodeSync_ChangeType_Mobile:
    case SendCodeSync_ChangeType_Login:
    case SendCodeSync_ChangeType_Mainphone:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
