// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserData.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "UserData.pbobjc.h"
 #import "FileData.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - UserDataRoot

@implementation UserDataRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - UserDataRoot_FileDescriptor

static GPBFileDescriptor *UserDataRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"protocol"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - UserItem

@implementation UserItem

@dynamic hasUserId, userId;
@dynamic hasUserName, userName;
@dynamic hasHeadIndex, headIndex;
@dynamic hasFileNum, fileNum;
@dynamic hasIsFriend, isFriend;
@dynamic hasIsOnline, isOnline;
@dynamic hasIsSpeed, isSpeed;
@dynamic hasIsRecommend, isRecommend;

typedef struct UserItem__storage_ {
  uint32_t _has_storage_[1];
  int32_t headIndex;
  int32_t fileNum;
  NSString *userId;
  NSString *userName;
} UserItem__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = UserItem_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UserItem__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userName",
        .dataTypeSpecific.className = NULL,
        .number = UserItem_FieldNumber_UserName,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(UserItem__storage_, userName),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "headIndex",
        .dataTypeSpecific.className = NULL,
        .number = UserItem_FieldNumber_HeadIndex,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(UserItem__storage_, headIndex),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "fileNum",
        .dataTypeSpecific.className = NULL,
        .number = UserItem_FieldNumber_FileNum,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(UserItem__storage_, fileNum),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "isFriend",
        .dataTypeSpecific.className = NULL,
        .number = UserItem_FieldNumber_IsFriend,
        .hasIndex = 4,
        .offset = 5,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "isOnline",
        .dataTypeSpecific.className = NULL,
        .number = UserItem_FieldNumber_IsOnline,
        .hasIndex = 6,
        .offset = 7,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "isSpeed",
        .dataTypeSpecific.className = NULL,
        .number = UserItem_FieldNumber_IsSpeed,
        .hasIndex = 8,
        .offset = 9,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "isRecommend",
        .dataTypeSpecific.className = NULL,
        .number = UserItem_FieldNumber_IsRecommend,
        .hasIndex = 10,
        .offset = 11,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UserItem class]
                                     rootClass:[UserDataRoot class]
                                          file:UserDataRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UserItem__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\010\001\006\000\002\010\000\003\t\000\004\007\000\005\010\000\006\010\000\007\007\000\010\013\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
