// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserData.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserDataRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserDataRoot : GPBRootObject
@end

#pragma mark - UserItem

typedef GPB_ENUM(UserItem_FieldNumber) {
  UserItem_FieldNumber_UserId = 1,
  UserItem_FieldNumber_UserName = 2,
  UserItem_FieldNumber_HeadIndex = 3,
  UserItem_FieldNumber_FileNum = 4,
  UserItem_FieldNumber_IsFriend = 5,
  UserItem_FieldNumber_IsOnline = 6,
};

@interface UserItem : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;
/** Test to see if @c userId has been set. */
@property(nonatomic, readwrite) BOOL hasUserId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

@property(nonatomic, readwrite) int32_t headIndex;

@property(nonatomic, readwrite) BOOL hasHeadIndex;
@property(nonatomic, readwrite) int32_t fileNum;

@property(nonatomic, readwrite) BOOL hasFileNum;
@property(nonatomic, readwrite) BOOL isFriend;

@property(nonatomic, readwrite) BOOL hasIsFriend;
@property(nonatomic, readwrite) BOOL isOnline;

@property(nonatomic, readwrite) BOOL hasIsOnline;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
